# Initial Setup stuff
url: "https://test.oldhamgroup.com"
plugins:
    - jekyll-sitemap
exclude:
  - .jekyll-cache

# TOG Collections
collections:
  flexo:
    output: true
    permalink: /:collection/:path/
  indsupply:
    output: true
    permalink: /:collection/:path/
  prepress:
    output: true
    permalink: /:collection/:path/
  supplies:
    output: true
    permalink: /:collection/:path/
  si:
    output: true
    permalink: /:collection/:path/
  wideformat:
    output: true
    permalink: /:collection/:path/

defaults:
 -  scope:
      path: ""
      type: flexo
    values:
      layout: inside
 -  scope:
      path: ""
      type: indsupply
    values:
      layout: inside
 -  scope:
      path: ""
      type: prepress
    values:
      layout: inside
 -  scope:
      path: ""
      type: supplies
    values:
      layout: inside
 -  scope:
      path: ""
      type: si
    values:
      layout: inside
 -  scope:
     path: ""
     type: wideformat
    values:
     layout: inside
